---                       # yamllint: document-start

name: End-to-End Syslog Testing

on:
  workflow_dispatch: {}

  # every 15 min, Monday-Friday, 09-17 US-Eastern
  schedule:
    # EDT (UTC-4)  — Mar-Oct
    - cron: "*/15 13-21 * 3-10 1-5"
    # EST (UTC-5)  — Nov-Feb
    - cron: "*/15 14-22 * 11,12,1,2 1-5"

  push:
    branches:
      - "main"
    paths:
      - 'rootless-syslog-ng/**'
      - 'shared/samples/**'
      - '.github/workflows/e2e-syslog-test.yml'

jobs:
  test-rootless-syslog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Write .env for rootless solution
        run: |
          cd rootless-syslog-ng
          echo "S1_WRITE_TOKEN=${{ secrets.S1_WRITE_TOKEN }}"  > .env
          echo "S1_INGEST_URL=${{ vars.S1_INGEST_URL }}"       >> .env
          echo "SYSLOG_PORT=${{ vars.SYSLOG_PORT || '5514' }}" >> .env
          
      - name: Verify environment variables are set
        run: |
          cd rootless-syslog-ng
          echo "Environment variables in .env:"
          cat .env

      - name: Start Rootless Syslog-NG
        run: |
          cd rootless-syslog-ng
          docker compose up -d

      - name: Wait for syslog-ng to be ready
        run: |
          echo "Waiting for syslog-ng to start..."
          sleep 10
          docker compose -f rootless-syslog-ng/docker-compose.yml ps

      - name: Test Linux logs
        env:
          SYSLOG_PORT: ${{ vars.SYSLOG_PORT || '5514' }}
        run: |
          set -euo pipefail
          # Use the portable command that works on all systems
          sed -E "s/[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z/$(date -u +'%Y-%m-%dT%H:%M:%SZ')/" \
            shared/samples/linux-sample.log |
            tee /dev/stderr |
            docker run -i --rm --network host \
              ghcr.io/sva-s1/alpine-nc:latest \
              /bin/ash -c "nc -u -w 2 127.0.0.1 ${SYSLOG_PORT}"

      - name: Test FortiGate logs
        env:
          SYSLOG_PORT: ${{ vars.SYSLOG_PORT || '5514' }}
        run: |
          set -euo pipefail

          # ── capture "now" once ─────────────────────────────────────────────
          NOW_EPOCH_NS="$(date +%s%N)"           # 19-digit nanoseconds
          NOW_EPOCH_S="${NOW_EPOCH_NS::10}"      # seconds

          CURRENT_DATE="$(date -u -d "@${NOW_EPOCH_S}" '+%Y-%m-%d')"
          CURRENT_TIME="$(date -u -d "@${NOW_EPOCH_S}" '+%H:%M:%S')"
          EVENTTIME="${NOW_EPOCH_NS}"

          sed -e "s/date=[0-9-]*/date=${CURRENT_DATE}/" \
              -e "s/time=[0-9:]\{8\}/time=${CURRENT_TIME}/" \
              -e "s/eventtime=[0-9]\{19\}/eventtime=${EVENTTIME}/" \
              shared/samples/fortigate-sample.log |
            tee /dev/stderr |
            docker run -i --rm --network host \
              ghcr.io/sva-s1/alpine-nc:latest \
              /bin/ash -c "nc -u -w 2 127.0.0.1 ${SYSLOG_PORT}"

      - name: Test Zscaler logs
        env:
          SYSLOG_PORT: ${{ vars.SYSLOG_PORT || '5514' }}
        run: |
          set -euo pipefail
          CURRENT_DATETIME=$(date '+%Y-%m-%d %H:%M:%S')
          sed "s/\"datetime\":\"[^\"]*\"/\"datetime\":\"$CURRENT_DATETIME\"/" \
            shared/samples/zscaler-sample.log |
            tee /dev/stderr |
            docker run -i --rm --network host \
              ghcr.io/sva-s1/alpine-nc:latest \
              /bin/ash -c "nc -u -w 2 127.0.0.1 ${SYSLOG_PORT}"

      - name: Display syslog-ng logs
        if: always()
        run: |
          cd rootless-syslog-ng
          docker compose logs

      - name: Cleanup
        if: always()
        run: |
          cd rootless-syslog-ng
          docker compose down
          rm -f .env