name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          # Get latest tag (if any)
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

          # Count total commits
          COMMIT_COUNT=$(git rev-list --count HEAD)

          # Build changelog
          if [ -z "$LAST_TAG" ]; then
            if [ "$COMMIT_COUNT" -lt 10 ]; then
              CHANGES=$(git log --pretty=format:"- %s" HEAD)
            else
              CHANGES=$(git log --pretty=format:"- %s" HEAD~10..HEAD)
            fi
          else
            CHANGES=$(git log --pretty=format:"- %s" "$LAST_TAG"..HEAD)
          fi

          {
            echo "CHANGES<<EOF"
            echo "$CHANGES"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
          name: "SentinelOne Syslog Toolkit ${{ github.ref_name }}"
          body: |
            ## SentinelOne Syslog Toolkit ${{ github.ref_name }}

            ### What's Changed
            ${{ steps.changelog.outputs.CHANGES }}

            ### Solutions Included
            - **Simple Collector** - Basic multi-port syslog collection
            - **3-in-1 Pipeline** - Advanced content-based log routing  
            - **Rootless Syslog-NG** - High-performance rootless deployment

            ### Quick Start
            ```bash
            git clone https://github.com/sva-s1/sentinelone-syslog-toolkit.git
            cd sentinelone-syslog-toolkit
            bash setup.sh
            ```

            ## 📦 Container Images (Primary Release Artifacts)

            ### Rootless Syslog-NG Container
            ```bash
            docker pull ghcr.io/sva-s1/syslog:${{ github.ref_name }}
            docker pull ghcr.io/sva-s1/syslog:latest
            ```
            **Package:** [📦 sva-s1/syslog](https://github.com/sva-s1/sentinelone-syslog-toolkit/pkgs/container/syslog)

            ### Alpine NetCat Utility
            ```bash
            docker pull ghcr.io/sva-s1/alpine-nc:latest
            ```
            **Package:** [📦 sva-s1/alpine-nc](https://github.com/sva-s1/sentinelone-syslog-toolkit/pkgs/container/alpine-nc)

            ### 🔄 Migration Notice
            **Previous container locations deprecated:**
            - Old: `ghcr.io/sva-s1/syslog` (from sva-s1/syslog repo) 
            - New: `ghcr.io/sva-s1/syslog` (from sva-s1/sentinelone-syslog-toolkit repo)

            ---

            ### 📋 Source Code
            **Recommended:** Use `git clone` for latest source code and setup scripts.

            The source code archives below are auto-generated by GitHub. For setup and deployment, use the container images above or clone the repository.

            For detailed setup instructions, see the README.md in each solution directory.
          draft: false
          prerelease: false
          generate_release_notes: false
          make_latest: true

  build-release-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Build and push release images
        uses: docker/build-push-action@v6
        with:
          context: ./rootless-syslog-ng
          file: ./rootless-syslog-ng/Dockerfiles/syslog-ng-rootless/Dockerfile
          push: true
          tags: |
            ghcr.io/sva-s1/syslog:${{ steps.version.outputs.version }}
            ghcr.io/sva-s1/syslog:latest
          platforms: linux/amd64
